### ISSUE TITLE
 Cannot invoke "javafx.scene.Node.getScene()" because "<local2>" is null

### ISSUE THREAD

**Issue by qiaoyi213** [qiaoyi213/TapMePlusOne#12]
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException: Cannot invoke "javafx.scene.Node.getScene()" because "<local2>" is null
	at javafx.graphics@19/javafx.scene.Scene$ScenePulseListener.synchronizeSceneNodes(Scene.java:2395)
	at javafx.graphics@19/javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2542)
	at javafx.graphics@19/com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Toolkit.java:407)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at javafx.graphics@19/com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:406)
	at javafx.graphics@19/com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:436)
	at javafx.graphics@19/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:575)
	at javafx.graphics@19/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:555)
	at javafx.graphics@19/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:548)
	at javafx.graphics@19/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:352)
	at javafx.graphics@19/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)

**Comment by flocrok** [comment]
Hi,
Is this issue still active or is it resolved ?
We encountered the same issue with our application and I would like to know if you found a solution.
We use JFX 17.0.6.
Regards

**Comment by qiaoyi213** [comment]
Hi,
Sorry, I could not found a specific point to solve this issue.
But you can check your GetScene() method is get the correct scene.
Or you can provide your repo on your GitHub so that I can try to help you as possible as I can.

Sincerely

**Comment by flocrok** [comment]
Hi,
I've found issues about this : 
https://bugs.openjdk.org/browse/JDK-8303736
https://bugs.openjdk.org/browse/JDK-8179676

So I've moved some styling code to the Java-FX thread.
Thanks for your reply.
